flows:
  knowledge:
    default: true
    globals:
      ingestion:
        textsplitter:
          chunkSize: 800
          chunkOverlap: 400
    ingestion:
      - filetypes: ["*"]
    retrieval:
      querymodifiers:
        # Enhance
        - name: enhance
          options:
            model:
              openai:
                apiKey: "${OPENAI_API_KEY}"
                model: gpt-4o
                apiType: OPEN_AI
                baseURL: "${OPENAI_BASE_URL}"
      retriever:
        name: basic
        options:
          topK: 20
      postprocessors:
        - name: similarity
          options:
            threshold: 0.6
        - name: reduce
          options:
            topK: 20



